[Service]
# Autologin no KMSCON usando /bin/login -f (force login sem senha)
# Nota: a flag --autologin NÃO existe no kmscon do Debian
ExecStart=
ExecStart=/usr/bin/kmscon --vt %I --seat seat0 --no-switchvt --font-name "Hack" --font-size 12 --login -- /bin/login -p -f root
