#!/usr/bin/env bash
# Generated by bash-performance-master. Requires Bash __BASH_MIN__+.
__STRICT_BLOCK__
shopt -s nullglob
# BP_COMPONENTS
# BP_COMPONENTS_END
bp_process_file() { local path=$1; printf 'TODO: process %q\n' "$path" >&2; return 64; }
bp_main() {
    local directory=${1:-.} path status=0
    [[ -d $directory ]] || { printf 'Not a directory: %s\n' "$directory" >&2; return 66; }
    for path in "$directory"/*; do
        [[ -f $path ]] || continue
        bp_process_file "$path" || status=$?
    done
    return "$status"
}
bp_main "$@"
