#!/usr/bin/env bash
# Generated by bash-performance-master. Requires Bash __BASH_MIN__+.
__STRICT_BLOCK__
# BP_COMPONENTS
# BP_COMPONENTS_END
bp_cleanup() { local status=$?; trap - EXIT INT TERM; if declare -F bp_remove_tempdir >/dev/null; then bp_remove_tempdir; fi; return "$status"; }
trap bp_cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
bp_main() { printf '%s\n' 'TODO: implement bp_main' >&2; return 64; }
bp_main "$@"
