#!/usr/bin/env bash
# Generated by bash-performance-master. Requires Bash __BASH_MIN__+.
__STRICT_BLOCK__
# BP_COMPONENTS
# BP_COMPONENTS_END
bp_process_record() { local record=$1; printf '%s\n' "$record"; }
bp_main() { local line; while IFS= read -r line || [[ -n $line ]]; do bp_process_record "$line"; done; }
bp_main "$@"
