#!/bin/sh
set -e

DEBIAN_VERSION="trixie"
ISO_NAME="debian-trixie-zbm"
ARCH="amd64"
LOCALE="pt_BR.UTF-8"
TIMEZONE="America/Sao_Paulo"
KEYBOARD="br"
MIRROR_CHROOT="http://ftp.br.debian.org/debian/"
MIRROR_BINARY="http://ftp.br.debian.org/debian/"

lb config noauto \
    --mode debian \
    --distribution "${DEBIAN_VERSION}" \
    --parent-mirror-chroot "${MIRROR_CHROOT}" \
    --parent-mirror-binary "${MIRROR_BINARY}" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --parent-archive-areas 'main contrib non-free-firmware non-free' \
    --architectures "${ARCH}" \
    --linux-flavours "${ARCH}" \
    --bootappend-live "boot=live components hostname=${ISO_NAME} locales=${LOCALE} timezone=${TIMEZONE} keyboard-layouts=${KEYBOARD} live-config.autologin console=tty0 console=ttyS0,115200n8" \
    --memtest none \
    --debian-installer none \
    --debian-installer-gui false \
    --bootloaders "syslinux,grub-efi" \
    --binary-images iso-hybrid \
    --checksums sha256 \
    --compression xz \
    --chroot-squashfs-compression-type zstd \
    --zsync false \
    --apt-recommends true \
    --apt-indices false \
    --cache-packages true \
    --debootstrap-options "--include=ca-certificates" \
    --security true \
    --backports true \
    --updates true \
    "${@}"
