#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Library: setup-zbm-config.sh
# Purpose: install/configure ZFSBootMenu inside target (UEFI) and create EFI entries (best-effort)
# Exports: zbm_setup_all
# Notes:
# - Designed to be lazy-loaded by installer-router.sh
# - Single-responsibility functions
# - No exits inside functions (return codes only)
# - All stderr messages via printf >&2

ZBM_TARGET_ROOT_DEFAULT="/mnt"
ZBM_ESP_MOUNT_DEFAULT="/boot/efi"
ZBM_EFI_DIR_DEFAULT="/EFI/ZFSBootMenu"
ZBM_LABEL_DEFAULT="ZFSBootMenu"
ZBM_ALLOWED_POOL_RE_DEFAULT='^[A-Za-z][A-Za-z0-9_.:-]{0,47}$'
ZBM_ALLOWED_DS_RE_DEFAULT='^[A-Za-z0-9_.:-]+(/[A-Za-z0-9_.:-]+)+$'
ZBM_ALLOWED_MOUNT_RE_DEFAULT='^/[^[:cntrl:]]*$'

stderr() { printf '%s\n' "$*" >&2; }
stdout() { printf '%s\n' "$*"; }

sanitize_ws() {
    local in; in="${1-}"
    in="${in//$'\r'/}"
    in="${in//$'\n'/}"
    printf '%s' "$in" | sed -E 's/[[:space:]]+/ /g; s/^ +//; s/ +$//'
}

sanitize_path() {
    local in; in="$(sanitize_ws "${1-}")"
    if [[ -z "$in" ]]; then
        printf '%s' ""
        return
    fi
    printf '%s' "$in" | sed -E 's/[[:cntrl:]]+//g'
}

sanitize_id() {
    local in; in="$(sanitize_ws "${1-}")"
    if [[ -z "$in" ]]; then
        printf '%s' ""
        return
    fi
    printf '%s' "$in" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_.:-]+/_/g; s/^_+//; s/_+$//'
}

require_cmd() {
    local cmd; cmd="$(sanitize_ws "${1-}")"
    if [[ -z "$cmd" ]]; then
        stderr "Erro: comando vazio."
        return 1
    fi
    if ! command -v "$cmd" >/dev/null 2>&1; then
        stderr "Erro: dependência ausente: $cmd"
        return 1
    fi
}

zbm_loaded() { :; }

zbm_is_poolname() {
    local p; p="$(sanitize_ws "${1-}")"
    [[ -n "$p" && "$p" =~ $ZBM_ALLOWED_POOL_RE_DEFAULT ]]
}

zbm_is_dataset() {
    local ds; ds="$(sanitize_ws "${1-}")"
    [[ -n "$ds" && "$ds" =~ $ZBM_ALLOWED_DS_RE_DEFAULT ]]
}

zbm_is_mountpoint_path() {
    local mp; mp="$(sanitize_path "${1-}")"
    [[ -n "$mp" && "$mp" =~ $ZBM_ALLOWED_MOUNT_RE_DEFAULT ]]
}

zbm_chroot_run() {
    # Single responsibility: run command in chroot
    # Args: target_root cmd
    local root; root="$(sanitize_path "${1-}")"
    local cmd; cmd="$(sanitize_ws "${2-}")"
    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi
    if [[ -z "$cmd" ]]; then
        stderr "Erro: comando chroot vazio."
        return 1
    fi
    require_cmd chroot || return 1
    if [[ "$cmd" == *$'\n'* || "$cmd" == *$'\0'* ]]; then
        stderr "Erro: comando chroot contém caracteres inválidos."
        return 1
    fi
    if ! chroot "$root" /usr/bin/env -i PATH=/usr/sbin:/usr/bin:/sbin:/bin /bin/bash -lc "$cmd" >/dev/null 2>&1; then
        stderr "Erro: chroot falhou: $cmd"
        return 1
    fi
}

zbm_install_packages_target() {
    # Single responsibility: install ZBM dependencies in target
    # Args: target_root
    local root; root="$(sanitize_path "${1-}")"
    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi

    # ZFSBootMenu packaging can vary; best-effort:
    # - try zfsbootmenu
    # - fallback to building from zfsbootmenu + dracut if available
    if declare -F installutils_apt_install_packages >/dev/null 2>&1; then
        installutils_apt_install_packages "$root" "zfsbootmenu" && return 0
        installutils_apt_install_packages "$root" "dracut-core dracut-network" || true
        installutils_apt_install_packages "$root" "curl gpg" || true
        return 0
    fi

    zbm_chroot_run "$root" "apt-get update" || return 1
    if zbm_chroot_run "$root" "DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install zfsbootmenu"; then
        return 0
    fi
    zbm_chroot_run "$root" "DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install dracut-core dracut-network curl gpg" || true
}

zbm_write_zbm_config_target() {
    # Single responsibility: write /etc/zfsbootmenu/config.yaml
    # Args: target_root pool root_dataset kernel_cmdline
    local root; root="$(sanitize_path "${1-}")"
    local pool; pool="$(sanitize_ws "${2-}")"
    local root_ds; root_ds="$(sanitize_ws "${3-}")"
    local cmdline; cmdline="$(sanitize_ws "${4-}")"

    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi
    if ! zbm_is_poolname "$pool"; then
        stderr "Erro: pool inválido: $pool"
        return 1
    fi
    if ! zbm_is_dataset "$root_ds"; then
        stderr "Erro: dataset inválido: $root_ds"
        return 1
    fi

    require_cmd mkdir || return 1
    mkdir -p "$root/etc/zfsbootmenu"

    local file
    file="$(sanitize_path "$root/etc/zfsbootmenu/config.yaml")"

    # Minimal sane config: hostid auto, pool import, kernel cmdline
    {
        printf '# Generated by fileserver-installer (ZFSBootMenu)\n'
        printf "Global:\n"
        printf "  ManageImages: true\n"
        printf "  BootMountPoint: /boot\n"
        printf "  DracutConfDir: /etc/zfsbootmenu/dracut.conf.d\n"
        printf "  PreHooksDir: /etc/zfsbootmenu/hooks\n"
        printf "  PostHooksDir: /etc/zfsbootmenu/hooks\n"
        printf "Components:\n"
        printf "  ImageDir: /boot/efi%s\n" "$ZBM_EFI_DIR_DEFAULT"
        printf "  Versions: 2\n"
        printf "EFI:\n"
        printf "  Enabled: true\n"
        printf "  ImageDir: /boot/efi%s\n" "$ZBM_EFI_DIR_DEFAULT"
        printf "  Versions: 2\n"
        printf "Kernel:\n"
        printf "  CommandLine: \"%s\"\n" "$(printf '%s' "$cmdline" | sed -E 's/\\/\\\\/g; s/"/\\"/g')"
        printf "ZFS:\n"
        printf "  Pool: \"%s\"\n" "$pool"
        printf "  Root: \"%s\"\n" "$root_ds"
    } >"$file"
}

zbm_ensure_efi_dirs_target() {
    # Single responsibility: ensure ZBM EFI dir exists under ESP mount in target
    # Args: target_root esp_mount_inside_target
    local root; root="$(sanitize_path "${1-}")"
    local esp; esp="$(sanitize_path "${2-}")"
    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi
    if [[ -z "$esp" ]]; then
        esp="$ZBM_ESP_MOUNT_DEFAULT"
    fi
    if ! zbm_is_mountpoint_path "$esp"; then
        stderr "Erro: esp mount inválido: $esp"
        return 1
    fi
    require_cmd mkdir || return 1
    mkdir -p "$root$esp$ZBM_EFI_DIR_DEFAULT"
}

zbm_build_images_target() {
    # Single responsibility: build ZFSBootMenu images in target
    # Args: target_root
    local root; root="$(sanitize_path "${1-}")"
    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi

    # Prefer zbm-builder if present; otherwise zfsbootmenu generate
    if zbm_chroot_run "$root" "command -v zbm-builder >/dev/null 2>&1"; then
        zbm_chroot_run "$root" "zbm-builder" || return 1
        return 0
    fi
    if zbm_chroot_run "$root" "command -v generate-zbm >/dev/null 2>&1"; then
        zbm_chroot_run "$root" "generate-zbm" || return 1
        return 0
    fi
    # Last resort: try zfsbootmenu initramfs build commands if known
    zbm_chroot_run "$root" "zfsbootmenu --debug --generate" || true
}

zbm_copy_images_to_esp_if_needed() {
    # Single responsibility: ensure EFI images exist under ESP dir (best-effort)
    # Args: target_root esp_mount_inside_target
    local root; root="$(sanitize_path "${1-}")"
    local esp; esp="$(sanitize_path "${2-}")"
    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi
    if [[ -z "$esp" ]]; then
        esp="$ZBM_ESP_MOUNT_DEFAULT"
    fi
    if ! zbm_is_mountpoint_path "$esp"; then
        stderr "Erro: esp mount inválido: $esp"
        return 1
    fi

    # Typical ZBM outputs into /boot/efi/EFI/ZFSBootMenu automatically when configured.
    # If not present, attempt to copy from /boot/ into ESP directory.
    local efi_dir; efi_dir="$(sanitize_path "$root$esp$ZBM_EFI_DIR_DEFAULT")"
    if [[ ! -d "$efi_dir" ]]; then
        return 1
    fi

    local src_candidates=()
    src_candidates+=("$root/boot/EFI/ZFSBootMenu")
    src_candidates+=("$root/boot/efi/EFI/ZFSBootMenu")
    src_candidates+=("$root/boot")
    src_candidates+=("$root/")

    local found=""
    local c
    for c in "${src_candidates[@]}"; do
        c="$(sanitize_path "$c")"
        if [[ -d "$c" ]]; then
            if find "$c" -maxdepth 2 -type f 2>/dev/null | grep -Eq '(ZFSBootMenu|zfsbootmenu|vmlinuz).*\.efi$'; then
                found="$c"
                break
            fi
        fi
    done

    if [[ -z "$found" ]]; then
        return 0
    fi

    require_cmd rsync || return 1
    rsync -a --delete "$found/" "$efi_dir/" >/dev/null 2>&1 || true
}

zbm_register_uefi_entry_best_effort() {
    # Single responsibility: create NVRAM boot entry if efibootmgr exists in chroot (best-effort)
    # Args: target_root disk esp_partnum efi_relpath label
    local root; root="$(sanitize_path "${1-}")"
    local disk; disk="$(sanitize_path "${2-}")"
    local espnum; espnum="$(sanitize_ws "${3-}")"
    local rel; rel="$(sanitize_ws "${4-}")"
    local label; label="$(sanitize_ws "${5-$ZBM_LABEL_DEFAULT}")"

    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi
    if [[ -z "$disk" || ! "$disk" =~ ^/dev/ ]]; then
        return 0
    fi
    if [[ -z "$espnum" ]] || ! printf '%s' "$espnum" | grep -Eq '^[0-9]+$'; then
        return 0
    fi
    if [[ -z "$rel" ]]; then
        return 0
    fi
    # efibootmgr expects Windows-style path
    local winrel
    winrel="$(printf '%s' "$rel" | sed -E 's|/|\\|g')"
    winrel="$(sanitize_ws "$winrel")"

    if ! zbm_chroot_run "$root" "command -v efibootmgr >/dev/null 2>&1"; then
        return 0
    fi

    # Requires efivars mounted in installer environment; may fail—best-effort
    zbm_chroot_run "$root" "efibootmgr -c -d '${disk}' -p '${espnum}' -L '${label}' -l '${winrel}'" || true
}

zbm_detect_esp_partnum_from_device() {
    # Single responsibility: infer partition number from /dev/...pN or ...N
    # Args: esp_part
    local esp; esp="$(sanitize_path "${1-}")"
    if [[ -z "$esp" ]]; then
        printf '%s' ""
        return 0
    fi
    local num
    num="$(printf '%s' "$esp" | sed -nE 's|.*p([0-9]+)$|\1|p; s|.*[^0-9]([0-9]+)$|\1|p' | tail -n1 || true)"
    num="$(sanitize_ws "$num")"
    if [[ -z "$num" ]] || ! printf '%s' "$num" | grep -Eq '^[0-9]+$'; then
        printf '%s' ""
        return 0
    fi
    printf '%s' "$num"
}

zbm_find_primary_efi_image_relpath() {
    # Single responsibility: choose a primary EFI image relpath inside ESP for NVRAM entry
    # Args: target_root esp_mount_inside_target
    local root; root="$(sanitize_path "${1-}")"
    local esp; esp="$(sanitize_path "${2-}")"
    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi
    if [[ -z "$esp" ]]; then
        esp="$ZBM_ESP_MOUNT_DEFAULT"
    fi

    local dir; dir="$(sanitize_path "$root$esp$ZBM_EFI_DIR_DEFAULT")"
    if [[ ! -d "$dir" ]]; then
        printf '%s' ""
        return 0
    fi

    local img
    img="$(find "$dir" -maxdepth 1 -type f -iname '*.efi' 2>/dev/null | sort | head -n1 || true)"
    img="$(sanitize_path "$img")"
    if [[ -z "$img" ]]; then
        printf '%s' ""
        return 0
    fi

    local rel
    rel="$(printf '%s' "$img" | sed -E "s|^${root}${esp}||")"
    rel="$(sanitize_ws "$rel")"
    printf '%s' "$rel"
}

zbm_setup_all() {
    # Single responsibility: orchestrate ZFSBootMenu setup in target
    # Args: target_root pool root_dataset esp_mount_inside_target kernel_cmdline do_nvram(1|0) [disk] [esp_part]
    local root; root="$(sanitize_path "${1-}")"
    local pool; pool="$(sanitize_ws "${2-}")"
    local root_ds; root_ds="$(sanitize_ws "${3-}")"
    local esp; esp="$(sanitize_path "${4-}")"
    local cmdline; cmdline="$(sanitize_ws "${5-}")"
    local do_nvram; do_nvram="$(sanitize_ws "${6-0}")"
    local disk; disk="$(sanitize_path "${7-}")"
    local esp_part; esp_part="$(sanitize_path "${8-}")"

    if [[ -z "$root" ]]; then
        root="$ZBM_TARGET_ROOT_DEFAULT"
    fi
    if [[ -z "$esp" ]]; then
        esp="$ZBM_ESP_MOUNT_DEFAULT"
    fi
    if [[ "$do_nvram" != "1" && "$do_nvram" != "0" ]]; then
        do_nvram="0"
    fi
    if [[ -z "$cmdline" ]]; then
        cmdline="root=ZFS=${root_ds}"
    fi

    if ! zbm_is_poolname "$pool"; then
        stderr "Erro: pool inválido: $pool"
        return 1
    fi
    if ! zbm_is_dataset "$root_ds"; then
        stderr "Erro: dataset inválido: $root_ds"
        return 1
    fi
    if ! zbm_is_mountpoint_path "$esp"; then
        stderr "Erro: esp mount inválido: $esp"
        return 1
    fi

    zbm_install_packages_target "$root" || return 1
    zbm_ensure_efi_dirs_target "$root" "$esp" || return 1
    zbm_write_zbm_config_target "$root" "$pool" "$root_ds" "$cmdline" || return 1
    zbm_build_images_target "$root" || true
    zbm_copy_images_to_esp_if_needed "$root" "$esp" || true

    if [[ "$do_nvram" == "1" && -n "$disk" && -n "$esp_part" ]]; then
        local partnum rel
        partnum="$(zbm_detect_esp_partnum_from_device "$esp_part")"
        rel="$(zbm_find_primary_efi_image_relpath "$root" "$esp")"
        rel="$(sanitize_ws "$rel")"
        if [[ -n "$partnum" && -n "$rel" ]]; then
            zbm_register_uefi_entry_best_effort "$root" "$disk" "$partnum" "$rel" "$ZBM_LABEL_DEFAULT" || true
        fi
    fi
}
