#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Library: finalize-chroot.sh
# Purpose: final target tweaks after bootloader install (optional): zfs mount cache, sysctl, services enable, network config best-effort
# Notes:
# - Designed to be lazy-loaded by installer-router.sh
# - Single-responsibility functions
# - No exits inside functions (return codes only)
# - All stderr messages via printf >&2

FINALIZE_TARGET_ROOT_DEFAULT="/mnt"

stderr() { printf '%s\n' "$*" >&2; }
stdout() { printf '%s' "$*"; }

sanitize_ws() {
    local in; in="${1-}"
    in="${in//$'\r'/}"
    in="${in//$'\n'/}"
    printf '%s' "$in" | sed -E 's/[[:space:]]+/ /g; s/^ +//; s/ +$//'
}

sanitize_path() {
    local in; in="$(sanitize_ws "${1-}")"
    if [[ -z "$in" ]]; then
        printf '%s' ""
        return
    fi
    printf '%s' "$in" | sed -E 's/[[:cntrl:]]+//g'
}

sanitize_id() {
    local in; in="$(sanitize_ws "${1-}")"
    if [[ -z "$in" ]]; then
        printf '%s' ""
        return
    fi
    printf '%s' "$in" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_.:-]+/_/g; s/^_+//; s/_+$//'
}

require_cmd() {
    local cmd; cmd="$(sanitize_ws "${1-}")"
    if [[ -z "$cmd" ]]; then
        stderr "Erro: comando vazio."
        return 1
    fi
    if ! command -v "$cmd" >/dev/null 2>&1; then
        stderr "Erro: dependência ausente: $cmd"
        return 1
    fi
}

finalize_loaded() { :; }

finalize_chroot_run() {
    # Single responsibility: run command inside chroot (quiet)
    # Args: target_root cmd
    local root; root="$(sanitize_path "${1-}")"
    local cmd; cmd="$(sanitize_ws "${2-}")"
    if [[ -z "$root" ]]; then
        root="$FINALIZE_TARGET_ROOT_DEFAULT"
    fi
    if [[ -z "$cmd" ]]; then
        stderr "Erro: comando chroot vazio."
        return 1
    fi
    require_cmd chroot || return 1
    if [[ "$cmd" == *$'\n'* || "$cmd" == *$'\0'* ]]; then
        stderr "Erro: comando chroot contém caracteres inválidos."
        return 1
    fi
    chroot "$root" /usr/bin/env -i PATH=/usr/sbin:/usr/bin:/sbin:/bin /bin/bash -lc "$cmd" >/dev/null 2>&1
}

finalize_enable_services_best_effort() {
    # Single responsibility: enable essential services if present
    # Args: target_root
    local root; root="$(sanitize_path "${1-}")"
    if [[ -z "$root" ]]; then
        root="$FINALIZE_TARGET_ROOT_DEFAULT"
    fi
    finalize_chroot_run "$root" "systemctl enable zfs-import-cache zfs-mount zfs.target" || true
    finalize_chroot_run "$root" "systemctl enable systemd-timesyncd" || true
    finalize_chroot_run "$root" "systemctl enable ssh" || true
}

finalize_write_sysctl_baseline() {
    # Single responsibility: write sysctl baseline for servers (safe defaults)
    # Args: target_root
    local root; root="$(sanitize_path "${1-}")"
    if [[ -z "$root" ]]; then
        root="$FINALIZE_TARGET_ROOT_DEFAULT"
    fi
    require_cmd mkdir || return 1
    mkdir -p "$root/etc/sysctl.d"

    local file
    file="$(sanitize_path "$root/etc/sysctl.d/99-fileserver-installer.conf")"
    {
        printf '# Generated by fileserver-installer (finalize)\n'
        printf 'vm.swappiness=10\n'
        printf 'fs.inotify.max_user_watches=1048576\n'
        printf 'net.core.default_qdisc=fq\n'
        printf 'net.ipv4.tcp_congestion_control=bbr\n'
    } >"$file"
}

finalize_write_zfs_modprobe_defaults() {
    # Single responsibility: ensure minimal ZFS module options file exists (do not override ARC here)
    # Args: target_root
    local root; root="$(sanitize_path "${1-}")"
    if [[ -z "$root" ]]; then
        root="$FINALIZE_TARGET_ROOT_DEFAULT"
    fi
    require_cmd mkdir || return 1
    mkdir -p "$root/etc/modprobe.d"

    local file
    file="$(sanitize_path "$root/etc/modprobe.d/zfs-installer-defaults.conf")"
    if [[ -f "$file" ]]; then
        return 0
    fi
    {
        printf '# Generated by fileserver-installer (finalize)\n'
        printf '# Keep conservative defaults; ARC max may be set elsewhere.\n'
        printf '# options zfs zfs_arc_max=<bytes>\n'
    } >"$file"
}

finalize_network_best_effort() {
    # Single responsibility: if manual network config is present in state, configure ifupdown file
    # Args: target_root iface method ip cidr gw dns
    local root; root="$(sanitize_path "${1-}")"
    local ifc; ifc="$(sanitize_ws "${2-}")"
    local method; method="$(sanitize_id "${3-dhcp}")"
    local ip4; ip4="$(sanitize_ws "${4-}")"
    local cidr; cidr="$(sanitize_ws "${5-}")"
    local gw; gw="$(sanitize_ws "${6-}")"
    local dns; dns="$(sanitize_ws "${7-}")"

    if [[ -z "$root" ]]; then
        root="$FINALIZE_TARGET_ROOT_DEFAULT"
    fi
    if [[ "$method" != "manual" ]]; then
        return 0
    fi
    if [[ -z "$ifc" || -z "$ip4" || -z "$cidr" || -z "$gw" ]]; then
        return 0
    fi
    if ! declare -F netutils_write_interfaces_static_target >/dev/null 2>&1; then
        return 0
    fi
    netutils_write_interfaces_static_target "$root" "$ifc" "$ip4" "$cidr" "$gw" "$dns" || true
}

finalize_all() {
    # Single responsibility: orchestrate finalize tasks (best-effort where safe)
    # Args: target_root pool hostname domain dns_list kernel_cmdline
    local root; root="$(sanitize_path "${1-}")"
    local pool; pool="$(sanitize_ws "${2-}")"
    local hn; hn="$(sanitize_ws "${3-}")"
    local dom; dom="$(sanitize_ws "${4-}")"
    local dns; dns="$(sanitize_ws "${5-}")"
    local cmdline; cmdline="$(sanitize_ws "${6-}")"

    if [[ -z "$root" ]]; then
        root="$FINALIZE_TARGET_ROOT_DEFAULT"
    fi

    finalize_write_sysctl_baseline "$root" || true
    finalize_write_zfs_modprobe_defaults "$root" || true
    finalize_enable_services_best_effort "$root" || true

    # Optional: ensure /etc/hostname and /etc/hosts correct (if postutils exists, prefer it)
    if declare -F postutils_set_hostname >/dev/null 2>&1; then
        postutils_set_hostname "$root" "$hn" "$dom" || true
    fi

    # Optional network for manual method: expects env variables exist in caller, but we only have dns here.
    if declare -F state_kv_get >/dev/null 2>&1; then
        local method ifc ip4 cidr gw
        method="$(sanitize_id "$(state_kv_get install_net_method)")"
        ifc="$(sanitize_ws "$(state_kv_get install_net_iface)")"
        ip4="$(sanitize_ws "$(state_kv_get install_net_ip)")"
        cidr="$(sanitize_ws "$(state_kv_get install_net_mask)")"
        gw="$(sanitize_ws "$(state_kv_get install_net_gw)")"
        finalize_network_best_effort "$root" "$ifc" "$method" "$ip4" "$cidr" "$gw" "$dns" || true
    fi

    # Optional: write cmdline hint for initramfs-tools (if present)
    if [[ -n "$cmdline" ]]; then
        require_cmd mkdir || return 1
        mkdir -p "$root/etc/default" || true
        printf '%s\n' "$cmdline" >"$(sanitize_path "$root/etc/default/grub.d/99-fileserver-installer-cmdline" )" 2>/dev/null || true
    fi

    # Optional: set zpool cachefile (if zpool exists in target)
    if [[ -n "$pool" ]]; then
        finalize_chroot_run "$root" "mkdir -p /etc/zfs && zpool set cachefile=/etc/zfs/zpool.cache '${pool}'" || true
    fi

    # Update initramfs again best-effort after tweaks
    finalize_chroot_run "$root" "update-initramfs -u -k all" || true
}
