#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Library: time-utils.sh
# Purpose: timezone listing and systemd-timesyncd config writer (target)
# Notes:
# - Designed to be lazy-loaded by installer-router.sh
# - Single-responsibility functions
# - No exits inside functions (return codes only)
# - All stderr messages via printf >&2

TIMEUTILS_TARGET_ROOT_DEFAULT="/mnt"

stderr() { printf '%s\n' "$*" >&2; }
stdout() { printf '%s' "$*"; }

sanitize_ws() {
    local in; in="${1-}"
    in="${in//$'\r'/}"
    in="${in//$'\n'/}"
    printf '%s' "$in" | sed -E 's/[[:space:]]+/ /g; s/^ +//; s/ +$//'
}

sanitize_path() {
    local in; in="$(sanitize_ws "${1-}")"
    if [[ -z "$in" ]]; then
        printf '%s' ""
        return
    fi
    printf '%s' "$in" | sed -E 's/[[:cntrl:]]+//g'
}

sanitize_id() {
    local in; in="$(sanitize_ws "${1-}")"
    if [[ -z "$in" ]]; then
        printf '%s' ""
        return
    fi
    printf '%s' "$in" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_.:-]+/_/g; s/^_+//; s/_+$//'
}

require_cmd() {
    local cmd; cmd="$(sanitize_ws "${1-}")"
    if [[ -z "$cmd" ]]; then
        stderr "Erro: comando vazio."
        return 1
    fi
    if ! command -v "$cmd" >/dev/null 2>&1; then
        stderr "Erro: dependência ausente: $cmd"
        return 1
    fi
}

timeutils_loaded() { :; }

timeutils_list_timezones() {
    # Single responsibility: list timezones (one per line) from tzdata database
    if [[ -d /usr/share/zoneinfo ]]; then
        require_cmd find || return 1
        require_cmd sed || return 1

        find /usr/share/zoneinfo -type f 2>/dev/null \
            | sed -E 's|^/usr/share/zoneinfo/||' \
            | sed -E '/^(posix|right|Etc\/GMT|Factory|localtime|posixrules)/d' \
            | sed -E '/^[[:space:]]*$/d' \
            | sort || true
        return 0
    fi

    if command -v timedatectl >/dev/null 2>&1; then
        timedatectl list-timezones 2>/dev/null || true
        return 0
    fi

    printf '%s\n' "UTC"
}

timeutils_configure_timesyncd_target() {
    # Single responsibility: configure systemd-timesyncd in target root
    # Args: target_root enable(1|0) server
    local root; root="$(sanitize_path "${1-}")"
    local enable; enable="$(sanitize_ws "${2-1}")"
    local server; server="$(sanitize_ws "${3-pool.ntp.org}")"

    if [[ -z "$root" ]]; then
        root="$TIMEUTILS_TARGET_ROOT_DEFAULT"
    fi
    if [[ "$enable" != "1" && "$enable" != "0" ]]; then
        enable="1"
    fi
    if [[ -z "$server" ]]; then
        server="pool.ntp.org"
    fi

    require_cmd mkdir || return 1
    mkdir -p "$root/etc/systemd"

    local file
    file="$(sanitize_path "$root/etc/systemd/timesyncd.conf")"

    if [[ "$enable" == "0" ]]; then
        {
            printf '# Generated by fileserver-installer (time-utils)\n'
            printf '[Time]\n'
            printf 'NTP=\n'
            printf 'FallbackNTP=\n'
        } >"$file"
        return 0
    fi

    {
        printf '# Generated by fileserver-installer (time-utils)\n'
        printf '[Time]\n'
        printf 'NTP=%s\n' "$server"
        printf 'FallbackNTP=pool.ntp.org time.cloudflare.com time.google.com\n'
    } >"$file"
}
