#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

# Library: net-utils.sh
# Purpose: network discovery/helpers for wizard (interfaces list) and static config writer (best-effort)
# Notes:
# - Designed to be lazy-loaded by installer-router.sh
# - Single-responsibility functions
# - No exits inside functions (return codes only)
# - All stderr messages via printf >&2

NETUTILS_ALLOWED_IFACE_RE_DEFAULT='^[a-zA-Z0-9_.:-]{1,32}$'
NETUTILS_TARGET_ROOT_DEFAULT="/mnt"

stderr() { printf '%s\n' "$*" >&2; }
stdout() { printf '%s' "$*"; }

sanitize_ws() {
    local in; in="${1-}"
    in="${in//$'\r'/}"
    in="${in//$'\n'/}"
    printf '%s' "$in" | sed -E 's/[[:space:]]+/ /g; s/^ +//; s/ +$//'
}

sanitize_id() {
    local in; in="$(sanitize_ws "${1-}")"
    if [[ -z "$in" ]]; then
        printf '%s' ""
        return
    fi
    printf '%s' "$in" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_.:-]+/_/g; s/^_+//; s/_+$//'
}

sanitize_path() {
    local in; in="$(sanitize_ws "${1-}")"
    if [[ -z "$in" ]]; then
        printf '%s' ""
        return
    fi
    printf '%s' "$in" | sed -E 's/[[:cntrl:]]+//g'
}

require_cmd() {
    local cmd; cmd="$(sanitize_ws "${1-}")"
    if [[ -z "$cmd" ]]; then
        stderr "Erro: comando vazio."
        return 1
    fi
    if ! command -v "$cmd" >/dev/null 2>&1; then
        stderr "Erro: dependência ausente: $cmd"
        return 1
    fi
}

netutils_loaded() { :; }

netutils_iface_is_valid() {
    local ifc; ifc="$(sanitize_ws "${1-}")"
    [[ -n "$ifc" && "$ifc" =~ $NETUTILS_ALLOWED_IFACE_RE_DEFAULT ]]
}

netutils_list_ifaces() {
    # Single responsibility: list candidate network interfaces (one per line)
    require_cmd ip || return 1
    require_cmd awk || return 1
    require_cmd sed || return 1

    # Exclude loopback and downed virtuals only if no carrier? (keep simple)
    local out
    out="$(ip -o link show 2>/dev/null \
        | awk -F': ' '{print $2}' \
        | sed -E 's/@.*$//; /^[[:space:]]*lo[[:space:]]*$/d' || true)"
    out="$(sanitize_ws "$out")"
    if [[ -z "$out" ]]; then
        printf '%s' ""
        return 0
    fi
    printf '%s\n' "$out"
}

netutils_get_iface_ipv4() {
    # Single responsibility: read IPv4 address of an interface (first), output "ip/cidr" or empty
    # Args: iface
    local ifc; ifc="$(sanitize_ws "${1-}")"
    if ! netutils_iface_is_valid "$ifc"; then
        stderr "Erro: iface inválida: $ifc"
        return 1
    fi
    require_cmd ip || return 1
    local out
    out="$(ip -4 -o addr show dev "$ifc" 2>/dev/null | awk '{print $4}' | head -n1 || true)"
    out="$(sanitize_ws "$out")"
    printf '%s' "$out"
}

netutils_write_interfaces_static_target() {
    # Single responsibility: write /etc/network/interfaces snippet (ifupdown) in target (best-effort)
    # Args: target_root iface ip cidr gw dns_list_space
    local root; root="$(sanitize_path "${1-}")"
    local ifc; ifc="$(sanitize_ws "${2-}")"
    local ip4; ip4="$(sanitize_ws "${3-}")"
    local cidr; cidr="$(sanitize_ws "${4-}")"
    local gw; gw="$(sanitize_ws "${5-}")"
    local dns; dns="$(sanitize_ws "${6-}")"

    if [[ -z "$root" ]]; then
        root="$NETUTILS_TARGET_ROOT_DEFAULT"
    fi
    if ! netutils_iface_is_valid "$ifc"; then
        stderr "Erro: iface inválida: $ifc"
        return 1
    fi
    if [[ -z "$ip4" || -z "$cidr" || -z "$gw" ]]; then
        stderr "Erro: ip/cidr/gw obrigatórios para static."
        return 1
    fi
    if ! printf '%s' "$cidr" | grep -Eq '^([0-9]|[12][0-9]|3[0-2])$'; then
        stderr "Erro: CIDR inválido: $cidr"
        return 1
    fi

    require_cmd mkdir || return 1
    mkdir -p "$root/etc/network"

    local file
    file="$(sanitize_path "$root/etc/network/interfaces")"

    # Convert CIDR -> netmask (simple awk)
    local netmask
    netmask="$(awk -v c="$cidr" '
        function m(n){return and(255, lshift(255, 8-n))}
        BEGIN{
            if(c<0||c>32){exit 1}
            a=int(c/8); b=c%8
            o1=(a>=1)?255: (a==0? (b? m(b):0):0)
            o2=(a>=2)?255: (a==1? (b? m(b):0):0)
            o3=(a>=3)?255: (a==2? (b? m(b):0):0)
            o4=(a>=4)?255: (a==3? (b? m(b):0):0)
            printf "%d.%d.%d.%d", o1,o2,o3,o4
        }' 2>/dev/null || true)"
    netmask="$(sanitize_ws "$netmask")"
    if [[ -z "$netmask" ]]; then
        stderr "Erro: falha ao converter CIDR->netmask."
        return 1
    fi

    {
        printf '# Generated by fileserver-installer (net-utils)\n'
        printf 'auto lo\n'
        printf 'iface lo inet loopback\n\n'
        printf 'auto %s\n' "$ifc"
        printf 'iface %s inet static\n' "$ifc"
        printf '    address %s\n' "$ip4"
        printf '    netmask %s\n' "$netmask"
        printf '    gateway %s\n' "$gw"
        if [[ -n "$dns" ]]; then
            printf '    dns-nameservers %s\n' "$dns"
        fi
        printf '\n'
    } >"$file"
}
